allowBuilds:
  '@sentry-internal/node-native-stacktrace': set this to true or false
  cpu-features: set this to true or false
  eslint-plugin-n8n-nodes-base: set this to true or false
  ssh2: set this to true or false
  unrs-resolver: set this to true or false
